### PR TITLE
CEDS-2281 Add Additional Documents Required as custom notification

### PR DESCRIPTION
**Pull request by PatrykRudnicki**

### CODE REVIEW

**Comment by iservport** [comment]
Can you update the readme file with `when LRN will start with D we will receive two notifications: ACCEPTED and ADDITIONAL_DOCUMENTS_REQUIRED. This can be used for testing the SFUS link on the notifications screen.`?

**Comment by PatrykRudnicki** [comment]
@iservport Good point. Actually there is no notes there, but I'll add description

**Comment by PatrykRudnicki** [comment]
@iservport It's done :)

**Comment by PatrykRudnicki** [comment]
It's stub, we don't have tests there, if you want I can cover all scenarios in tests

**Pull request merged**
